package com.bulkprocessing;

import java.util.HashMap;
import java.util.logging.Logger;

public class Configuration {
    static final Logger logger = Logger.getLogger("MakeFile");
    static final String FILE_NAME = "test.csv";
    static final HashMap COUNTRY_CODE_MAP = new HashMap();
    static {
        COUNTRY_CODE_MAP.put("Andorra, Principality Of", "AD");
        COUNTRY_CODE_MAP.put("United Arab Emirates", "AE");
        COUNTRY_CODE_MAP.put("Afghanistan, Islamic State Of", "AF");
        COUNTRY_CODE_MAP.put("Antigua And Barbuda", "AG");
        COUNTRY_CODE_MAP.put("Anguilla", "AI");
        COUNTRY_CODE_MAP.put("Albania", "AL");
        COUNTRY_CODE_MAP.put("Armenia", "AM");
        COUNTRY_CODE_MAP.put("Netherlands Antilles", "AN");
        COUNTRY_CODE_MAP.put("Angola", "AO");
        COUNTRY_CODE_MAP.put("Antarctica", "AQ");
        COUNTRY_CODE_MAP.put("Argentina", "AR");
        COUNTRY_CODE_MAP.put("American Samoa", "AS");
        COUNTRY_CODE_MAP.put("Austria", "AT");
        COUNTRY_CODE_MAP.put("Australia", "AU");
        COUNTRY_CODE_MAP.put("Aruba", "AW");
        COUNTRY_CODE_MAP.put("Azerbaidjan", "AZ");
        COUNTRY_CODE_MAP.put("Bosnia-Herzegovina", "BA");
        COUNTRY_CODE_MAP.put("Barbados", "BB");
        COUNTRY_CODE_MAP.put("Bangladesh", "BD");
        COUNTRY_CODE_MAP.put("Belgium", "BE");
        COUNTRY_CODE_MAP.put("Burkina Faso", "BF");
        COUNTRY_CODE_MAP.put("Bulgaria", "BG");
        COUNTRY_CODE_MAP.put("Bahrain", "BH");
        COUNTRY_CODE_MAP.put("Burundi", "BI");
        COUNTRY_CODE_MAP.put("Benin", "BJ");
        COUNTRY_CODE_MAP.put("Bermuda", "BM");
        COUNTRY_CODE_MAP.put("Brunei Darussalam", "BN");
        COUNTRY_CODE_MAP.put("Bolivia", "BO");
        COUNTRY_CODE_MAP.put("Brazil", "BR");
        COUNTRY_CODE_MAP.put("Bahamas", "BS");
        COUNTRY_CODE_MAP.put("Bhutan", "BT");
        COUNTRY_CODE_MAP.put("Bouvet Island", "BV");
        COUNTRY_CODE_MAP.put("Botswana", "BW");
        COUNTRY_CODE_MAP.put("Belarus", "BY");
        COUNTRY_CODE_MAP.put("Belize", "BZ");
        COUNTRY_CODE_MAP.put("Canada", "CA");
        COUNTRY_CODE_MAP.put("Cocos (Keeling) Islands", "CC");
        COUNTRY_CODE_MAP.put("Central African Republic", "CF");
        COUNTRY_CODE_MAP.put("Congo, The Democratic Republic Of The", "CD");
        COUNTRY_CODE_MAP.put("Congo", "CG");
        COUNTRY_CODE_MAP.put("Switzerland", "CH");
        COUNTRY_CODE_MAP.put("Ivory Coast (Cote D'Ivoire)", "CI");
        COUNTRY_CODE_MAP.put("Cook Islands", "CK");
        COUNTRY_CODE_MAP.put("Chile", "CL");
        COUNTRY_CODE_MAP.put("Cameroon", "CM");
        COUNTRY_CODE_MAP.put("China", "CN");
        COUNTRY_CODE_MAP.put("Colombia", "CO");
        COUNTRY_CODE_MAP.put("Costa Rica", "CR");
        COUNTRY_CODE_MAP.put("Former Czechoslovakia", "CS");
        COUNTRY_CODE_MAP.put("Cuba", "CU");
        COUNTRY_CODE_MAP.put("Cape Verde", "CV");
        COUNTRY_CODE_MAP.put("Christmas Island", "CX");
        COUNTRY_CODE_MAP.put("Cyprus", "CY");
        COUNTRY_CODE_MAP.put("Czech Republic", "CZ");
        COUNTRY_CODE_MAP.put("Germany", "DE");
        COUNTRY_CODE_MAP.put("Djibouti", "DJ");
        COUNTRY_CODE_MAP.put("Denmark", "DK");
        COUNTRY_CODE_MAP.put("Dominica", "DM");
        COUNTRY_CODE_MAP.put("Dominican Republic", "DO");
        COUNTRY_CODE_MAP.put("Algeria", "DZ");
        COUNTRY_CODE_MAP.put("Ecuador", "EC");
        COUNTRY_CODE_MAP.put("Estonia", "EE");
        COUNTRY_CODE_MAP.put("Egypt", "EG");
        COUNTRY_CODE_MAP.put("Western Sahara", "EH");
        COUNTRY_CODE_MAP.put("Eritrea", "ER");
        COUNTRY_CODE_MAP.put("Spain", "ES");
        COUNTRY_CODE_MAP.put("Ethiopia", "ET");
        COUNTRY_CODE_MAP.put("Finland", "FI");
        COUNTRY_CODE_MAP.put("Fiji", "FJ");
        COUNTRY_CODE_MAP.put("Falkland Islands", "FK");
        COUNTRY_CODE_MAP.put("Micronesia", "FM");
        COUNTRY_CODE_MAP.put("Faroe Islands", "FO");
        COUNTRY_CODE_MAP.put("France", "FR");
        COUNTRY_CODE_MAP.put("France (European Territory)", "FX");
        COUNTRY_CODE_MAP.put("Gabon", "GA");
        COUNTRY_CODE_MAP.put("Great Britain", "UK");
        COUNTRY_CODE_MAP.put("Grenada", "GD");
        COUNTRY_CODE_MAP.put("Georgia", "GE");
        COUNTRY_CODE_MAP.put("French Guyana", "GF");
        COUNTRY_CODE_MAP.put("Ghana", "GH");
        COUNTRY_CODE_MAP.put("Gibraltar", "GI");
        COUNTRY_CODE_MAP.put("Greenland", "GL");
        COUNTRY_CODE_MAP.put("Gambia", "GM");
        COUNTRY_CODE_MAP.put("Guinea", "GN");
        COUNTRY_CODE_MAP.put("Guadeloupe (French)", "GP");
        COUNTRY_CODE_MAP.put("Equatorial Guinea", "GQ");
        COUNTRY_CODE_MAP.put("Greece", "GR");
        COUNTRY_CODE_MAP.put("S. Georgia & S. Sandwich Isls.", "GS");
        COUNTRY_CODE_MAP.put("Guatemala", "GT");
        COUNTRY_CODE_MAP.put("Guam (USA)", "GU");
        COUNTRY_CODE_MAP.put("Guinea Bissau", "GW");
        COUNTRY_CODE_MAP.put("Guyana", "GY");
        COUNTRY_CODE_MAP.put("Hong Kong", "HK");
        COUNTRY_CODE_MAP.put("Heard And McDonald Islands", "HM");
        COUNTRY_CODE_MAP.put("Honduras", "HN");
        COUNTRY_CODE_MAP.put("Croatia", "HR");
        COUNTRY_CODE_MAP.put("Haiti", "HT");
        COUNTRY_CODE_MAP.put("Hungary", "HU");
        COUNTRY_CODE_MAP.put("Indonesia", "ID");
        COUNTRY_CODE_MAP.put("Ireland", "IE");
        COUNTRY_CODE_MAP.put("Israel", "IL");
        COUNTRY_CODE_MAP.put("India", "IN");
        COUNTRY_CODE_MAP.put("British Indian Ocean Territory", "IO");
        COUNTRY_CODE_MAP.put("Iraq", "IQ");
        COUNTRY_CODE_MAP.put("Iran", "IR");
        COUNTRY_CODE_MAP.put("Iceland", "IS");
        COUNTRY_CODE_MAP.put("Italy", "IT");
        COUNTRY_CODE_MAP.put("Jamaica", "JM");
        COUNTRY_CODE_MAP.put("Jordan", "JO");
        COUNTRY_CODE_MAP.put("Japan", "JP");
        COUNTRY_CODE_MAP.put("Kenya", "KE");
        COUNTRY_CODE_MAP.put("Kyrgyz Republic (Kyrgyzstan)", "KG");
        COUNTRY_CODE_MAP.put("Cambodia, Kingdom Of", "KH");
        COUNTRY_CODE_MAP.put("Kiribati", "KI");
        COUNTRY_CODE_MAP.put("Comoros", "KM");
        COUNTRY_CODE_MAP.put("Saint Kitts & Nevis Anguilla", "KN");
        COUNTRY_CODE_MAP.put("North Korea", "KP");
        COUNTRY_CODE_MAP.put("South Korea", "KR");
        COUNTRY_CODE_MAP.put("Kuwait", "KW");
        COUNTRY_CODE_MAP.put("Cayman Islands", "KY");
        COUNTRY_CODE_MAP.put("Kazakhstan", "KZ");
        COUNTRY_CODE_MAP.put("Laos", "LA");
        COUNTRY_CODE_MAP.put("Lebanon", "LB");
        COUNTRY_CODE_MAP.put("Saint Lucia", "LC");
        COUNTRY_CODE_MAP.put("Liechtenstein", "LI");
        COUNTRY_CODE_MAP.put("Sri Lanka", "LK");
        COUNTRY_CODE_MAP.put("Liberia", "LR");
        COUNTRY_CODE_MAP.put("Lesotho", "LS");
        COUNTRY_CODE_MAP.put("Lithuania", "LT");
        COUNTRY_CODE_MAP.put("Luxembourg", "LU");
        COUNTRY_CODE_MAP.put("Latvia", "LV");
        COUNTRY_CODE_MAP.put("Libya", "LY");
        COUNTRY_CODE_MAP.put("Morocco", "MA");
        COUNTRY_CODE_MAP.put("Monaco", "MC");
        COUNTRY_CODE_MAP.put("Moldavia", "MD");
        COUNTRY_CODE_MAP.put("Madagascar", "MG");
        COUNTRY_CODE_MAP.put("Marshall Islands", "MH");
        COUNTRY_CODE_MAP.put("Macedonia", "MK");
        COUNTRY_CODE_MAP.put("Mali", "ML");
        COUNTRY_CODE_MAP.put("Myanmar", "MM");
        COUNTRY_CODE_MAP.put("Mongolia", "MN");
        COUNTRY_CODE_MAP.put("Macau", "MO");
        COUNTRY_CODE_MAP.put("Northern Mariana Islands", "MP");
        COUNTRY_CODE_MAP.put("Martinique (French)", "MQ");
        COUNTRY_CODE_MAP.put("Mauritania", "MR");
        COUNTRY_CODE_MAP.put("Montserrat", "MS");
        COUNTRY_CODE_MAP.put("Malta", "MT");
        COUNTRY_CODE_MAP.put("Mauritius", "MU");
        COUNTRY_CODE_MAP.put("Maldives", "MV");
        COUNTRY_CODE_MAP.put("Malawi", "MW");
        COUNTRY_CODE_MAP.put("Mexico", "MX");
        COUNTRY_CODE_MAP.put("Malaysia", "MY");
        COUNTRY_CODE_MAP.put("Mozambique", "MZ");
        COUNTRY_CODE_MAP.put("Namibia", "NA");
        COUNTRY_CODE_MAP.put("New Caledonia (French)", "NC");
        COUNTRY_CODE_MAP.put("Niger", "NE");
        COUNTRY_CODE_MAP.put("Norfolk Island", "NF");
        COUNTRY_CODE_MAP.put("Nigeria", "NG");
        COUNTRY_CODE_MAP.put("Nicaragua", "NI");
        COUNTRY_CODE_MAP.put("Netherlands", "NL");
        COUNTRY_CODE_MAP.put("Norway", "NO");
        COUNTRY_CODE_MAP.put("Nepal", "NP");
        COUNTRY_CODE_MAP.put("Nauru", "NR");
        COUNTRY_CODE_MAP.put("Neutral Zone", "NT");
        COUNTRY_CODE_MAP.put("Niue", "NU");
        COUNTRY_CODE_MAP.put("New Zealand", "NZ");
        COUNTRY_CODE_MAP.put("Oman", "OM");
        COUNTRY_CODE_MAP.put("Panama", "PA");
        COUNTRY_CODE_MAP.put("Peru", "PE");
        COUNTRY_CODE_MAP.put("Polynesia (French)", "PF");
        COUNTRY_CODE_MAP.put("Papua New Guinea", "PG");
        COUNTRY_CODE_MAP.put("Philippines", "PH");
        COUNTRY_CODE_MAP.put("Pakistan", "PK");
        COUNTRY_CODE_MAP.put("Poland", "PL");
        COUNTRY_CODE_MAP.put("Saint Pierre And Miquelon", "PM");
        COUNTRY_CODE_MAP.put("Pitcairn Island", "PN");
        COUNTRY_CODE_MAP.put("Puerto Rico", "PR");
        COUNTRY_CODE_MAP.put("Portugal", "PT");
        COUNTRY_CODE_MAP.put("Palau", "PW");
        COUNTRY_CODE_MAP.put("Paraguay", "PY");
        COUNTRY_CODE_MAP.put("Qatar", "QA");
        COUNTRY_CODE_MAP.put("Reunion (French)", "RE");
        COUNTRY_CODE_MAP.put("Romania", "RO");
        COUNTRY_CODE_MAP.put("Russian Federation", "RU");
        COUNTRY_CODE_MAP.put("Rwanda", "RW");
        COUNTRY_CODE_MAP.put("Saudi Arabia", "SA");
        COUNTRY_CODE_MAP.put("Solomon Islands", "SB");
        COUNTRY_CODE_MAP.put("Seychelles", "SC");
        COUNTRY_CODE_MAP.put("Sudan", "SD");
        COUNTRY_CODE_MAP.put("Sweden", "SE");
        COUNTRY_CODE_MAP.put("Singapore", "SG");
        COUNTRY_CODE_MAP.put("Saint Helena", "SH");
        COUNTRY_CODE_MAP.put("Slovenia", "SI");
        COUNTRY_CODE_MAP.put("Svalbard And Jan Mayen Islands", "SJ");
        COUNTRY_CODE_MAP.put("Slovak Republic", "SK");
        COUNTRY_CODE_MAP.put("Sierra Leone", "SL");
        COUNTRY_CODE_MAP.put("San Marino", "SM");
        COUNTRY_CODE_MAP.put("Senegal", "SN");
        COUNTRY_CODE_MAP.put("Somalia", "SO");
        COUNTRY_CODE_MAP.put("Suriname", "SR");
        COUNTRY_CODE_MAP.put("Saint Tome (Sao Tome) And Principe", "ST");
        COUNTRY_CODE_MAP.put("Former USSR", "SU");
        COUNTRY_CODE_MAP.put("El Salvador", "SV");
        COUNTRY_CODE_MAP.put("Syria", "SY");
        COUNTRY_CODE_MAP.put("Swaziland", "SZ");
        COUNTRY_CODE_MAP.put("Turks And Caicos Islands", "TC");
        COUNTRY_CODE_MAP.put("Chad", "TD");
        COUNTRY_CODE_MAP.put("French Southern Territories", "TF");
        COUNTRY_CODE_MAP.put("Togo", "TG");
        COUNTRY_CODE_MAP.put("Thailand", "TH");
        COUNTRY_CODE_MAP.put("Tadjikistan", "TJ");
        COUNTRY_CODE_MAP.put("Tokelau", "TK");
        COUNTRY_CODE_MAP.put("Turkmenistan", "TM");
        COUNTRY_CODE_MAP.put("Tunisia", "TN");
        COUNTRY_CODE_MAP.put("Tonga", "TO");
        COUNTRY_CODE_MAP.put("East Timor", "TP");
        COUNTRY_CODE_MAP.put("Turkey", "TR");
        COUNTRY_CODE_MAP.put("Trinidad And Tobago", "TT");
        COUNTRY_CODE_MAP.put("Tuvalu", "TV");
        COUNTRY_CODE_MAP.put("Taiwan", "TW");
        COUNTRY_CODE_MAP.put("Tanzania", "TZ");
        COUNTRY_CODE_MAP.put("Ukraine", "UA");
        COUNTRY_CODE_MAP.put("Uganda", "UG");
        COUNTRY_CODE_MAP.put("United Kingdom", "UK");
        COUNTRY_CODE_MAP.put("USA Minor Outlying Islands", "UM");
        COUNTRY_CODE_MAP.put("United States", "US");
        COUNTRY_CODE_MAP.put("Uruguay", "UY");
        COUNTRY_CODE_MAP.put("Uzbekistan", "UZ");
        COUNTRY_CODE_MAP.put("Holy See (Vatican City State)", "VA");
        COUNTRY_CODE_MAP.put("Saint Vincent & Grenadines", "VC");
        COUNTRY_CODE_MAP.put("Venezuela", "VE");
        COUNTRY_CODE_MAP.put("Virgin Islands (British)", "VG");
        COUNTRY_CODE_MAP.put("Virgin Islands (USA)", "VI");
        COUNTRY_CODE_MAP.put("Vietnam", "VN");
        COUNTRY_CODE_MAP.put("Vanuatu", "VU");
        COUNTRY_CODE_MAP.put("Wallis And Futuna Islands", "WF");
        COUNTRY_CODE_MAP.put("Samoa", "WS");
        COUNTRY_CODE_MAP.put("Yemen", "YE");
        COUNTRY_CODE_MAP.put("Mayotte", "YT");
        COUNTRY_CODE_MAP.put("Yugoslavia", "YU");
        COUNTRY_CODE_MAP.put("South Africa", "ZA");
        COUNTRY_CODE_MAP.put("Zambia", "ZM");
        COUNTRY_CODE_MAP.put("Zaire", "ZR");
        COUNTRY_CODE_MAP.put("Zimbabwe", "ZW");

    }

}
